version: '3.8'
services:
  nextjs-app:
    build: .
    ports:
      - "3010:3000"  # Host port 3010 -> Container port 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --hostname 0.0.0.0
    container_name: polling-app-testing  # Clear name to avoid confusion
    networks:
      - polling-network

networks:
  polling-network:
    driver: bridge